config/routes.rb
Rails.application.routes.draw do
  get 'greenpoints/new'
  post 'greenpoints/create' 
  get 'greenpoints/edit'
  post 'greenpoints/update'

devise_for :users, controllers: {registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

resources :coupons
resources :events

get 'publicevents' => 'events#publicevents'
get 'confirmed/:id' => 'events#confirmed'
post 'eventships/:id' => 'events#eventships'


devise_scope :user do
post '/auth/google_oauth2/callback' => 'omniauth_callbacks#google_oauth2'
end

  root to: "home#index"
  get '/dash' => 'home#userdash'
  get '/business' => 'home#businessdash'
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  validates :expiration, presence: true
  belongs_to :business
  has_and_belongs_to_many :users

  def self.nearestcoupons(user)
	 nearest = []
	  	if user.business
	 	 all =  Coupon.all.where.not(business_id: user.business_id)
	 	 all.each do |coupon|
	 	 	nearest << coupon if coupon.business.zipcode == user.zipcode
	 	 	return nearest 
	 	 	end
	 	else 
	 		Coupon.all.each do |coupon|
	 	 	nearest << coupon if coupon.business.zipcode == user.zipcode
	 	 	return nearest 
	 		 end
	 	end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)
    @coupon.business_id = current_user.business.id
    respond_to do |format|
      if @coupon.save
        format.html { redirect_to '/business', notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:title, :description, :amount, :business_id, :expiration)
    end
    
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<div class="border-form-div">

  <%= form_for(@coupon) do |f| %>
    <% if @coupon.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

        <ul>
        <% @coupon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description,class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :value %>
      <%= f.number_field :amount, in: 0..100, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :expiration_date %><br>
      <%= f.datetime_select :expiration, class: "form-control", order: [ :month,:day, :year], ampm: true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

</div>

<div class="modal fade couponsurvey">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
              <!-- Close button -->
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close">&times;</span>
              </button>
            <h1>Have you improve your business Footprint?</h1>
            </div>
            <div class="modal-body">
               <ul class="list-group">
                <li class="list-group-item">
                    <div class="row">
                      <h3 class="text-center">Electricity points <span class="badge">3</span></h3>
                      <div class="well" style="overflow: auto;">
                      <ul class="list-group checked-list-box electricity">
                            <li class="list-group-item">Turning off lights at night</li>
                            <li class="list-group-item" data-checked="true">Using fans during the winter</li>
                            <li class="list-group-item">Using responsible energy sources(solar, wind, etc)</li>
                          </ul>
                      </div>
                  </div>
                </li>
                <li class="list-group-item">
                  <h3 class="text-center">Recycling <span class="badge">2</span></h3>
                  <ul class="list-group checked-list-box recycling">
                      <li class="list-group-item">Reclying bottles & cans</li>
                      <li class="list-group-item" data-checked="true">Reusing silverware & plates whenever possible</li>
                      <li class="list-group-item">Waste reduction</li>
                    </ul>
                </li>
                <li class="list-group-item">
                    <h3 class="text-center">Business transportation<span class="badge">1</span></h3>
                    <ul class="list-group checked-list-box transportation">
                          <li class="list-group-item">Frequent flyer</li>
                          <li class="list-group-item" data-checked="true">Frequent road/sea freights necessary</li>
                          <li class="list-group-item">More than one driver associated to business full-time</li>
                        </ul>
                </li>
                <button type="button" class="btn btn-primary btn-lg btn-block continue">Continue</button>
              </ul>
            </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Business</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.title %></td>
        <td><%= coupon.description %></td>
        <td><%= coupon.amount %></td>
        <td><%= coupon.business_id %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<%= render 'form' %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @coupon.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coupon.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @coupon.amount %>
</p>

<p>
  <strong>Business:</strong>
  <%= @coupon.business_id %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>