config/routes.rb
Rails.application.routes.draw do
  get 'greenpoints/new'
  post 'greenpoints/create' 
  get 'greenpoints/edit'
  post 'greenpoints/update'

devise_for :users, controllers: {registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

resources :coupons
resources :events

get 'publicevents' => 'events#publicevents'
get 'confirmed/:id' => 'events#confirmed'
post 'eventships/:id' => 'events#eventships'


devise_scope :user do
post '/auth/google_oauth2/callback' => 'omniauth_callbacks#google_oauth2'
end

  root to: "home#index"
  get '/dash' => 'home#userdash'
  get '/business' => 'home#businessdash'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResponsibleUs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="page-<%=action_name%>" data-spy="scroll" data-target=".navbar-fixed-top" data-userpage="<%=action_name%>">
 <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Responsible</span> 
                <%if current_user %>  
                    <%if current_user.business %>   
                    <%= current_user.business.name %>
                    <% elsif current_user.full_name.present? %>
                    <%= current_user.full_name %>
                    <% else %>
                    you
                     <% end %> 
                <%else %>
                us
                <%end%>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <%if current_user %>
                         <li>
                        <%= link_to('Home', root_path)%>
                        </li>
                        <li>
                        <%= link_to('Business Dashboard', business_path) if current_user.business%>
                        </li>
                        <li>
                        <%= link_to('Dashboard', dash_path)%>
                        </li>
                        <li>
                        <%= link_to('Green Events', events_path)%>
                        </li>
                        <li>
                        <%= link_to('log out', destroy_user_session_path, method: :delete)%>
                        </li>
                    <%elsif current_user.nil? && (current_page?(new_user_session_path) || current_page?(new_user_registration_path)) %>
                        <li>
                        <%= link_to('log in',  new_user_session_path)%>
                        </li>
                        <li>
                        <%= link_to('Home', root_path)%>
                        </li>
                    <%else %>
                        <li>
                        <%= link_to('log in',  new_user_session_path)%>
                        </li>
                        <li>
                        <a class="page-scroll" href="#about">About</a>
                        </li>
                        <li>
                        <a class="page-scroll" href="#How-to">How-to</a>
                        </li>
                        <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                        </li>
                    <%end%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<%= yield %>

 <%= javascript_include_tag 'application' %>
</body>
</html>